    DROP TABLE IF EXISTS Roles;  
    CREATE TABLE Roles (  
    Id INT AUTO_INCREMENT  PRIMARY KEY,
    Role_Name VARCHAR(50) NOT NULL,  
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
    ); 

    DROP TABLE IF EXISTS User;  
    CREATE TABLE User (  
    Id INT AUTO_INCREMENT  PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    User_Name VARCHAR(50) NOT NULL,    
    Password VARCHAR(50) NOT NULL,  
    Role_Id INTEGER NOT NULL,  
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    FOREIGN KEY (Role_Id) REFERENCES Roles(Id)
    ); 

    DROP TABLE IF EXISTS Message;  
    CREATE TABLE Message (  
    Id INT AUTO_INCREMENT  PRIMARY KEY,
    Message VARCHAR(50) NOT NULL,
    MessageFrom INTEGER NOT NULL,
    MessageTo INTEGER NOT NULL,  
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MessageFrom, MessageTo) REFERENCES User(Id, Id)
    );  
      